# Given two strings s and t which consist of only lowercase letters.
# String t is generated by random shuffling string s and then add one more letter at a random position.
# Find the letter that was added in t.

# Example:
# Input:
# s = "abcd"
# t = "abcde"
# Output:
# e
# Explanation:
# 'e' is the letter that was added.

import collections
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:

        # S1.
        # seen = collections.defaultdict(int)
        # for c in t:
        #     seen[c] += 1
        # for c in s:
        #     seen[c] -= 1
        #     if not seen[c]:
        #         del seen[c]
        # return list(seen.keys())[0]

        # S2.
        for c in set(t):
            if t.count(c) > s.count(c):
                return c

def main():
    s = Solution()
    print(s.findTheDifference(s = "abcd", t = "abcde"))

if __name__ == "__main__":
    main()